version: '3'

services:

  postgres_cocaines:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - postgres_cocaines:/var/lib/postgresql/data

  postgres_members:
    image: postgres:14.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - postgres_members:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222

volumes:
  postgres_members:
  postgres_cocaines:
  redis:
